payload:
  - PROCESS-NAME,System
  - PROCESS-NAME,wininit.exe
  - PROCESS-NAME,services.exe
  - PROCESS-NAME,mihomo.exe
  - PROCESS-NAME,clash-core.exe
  - PROCESS-NAME,clash-meta.exe
  - PROCESS-NAME,v2ray.exe
  - PROCESS-NAME,xray.exe
  - PROCESS-NAME,sing-box.exe
  - PROCESS-NAME,v2rayN.exe
  - PROCESS-NAME,nekobox.exe
  - PROCESS-NAME,Clash Verge.exe
  - PROCESS-NAME,Clash.exe
  - PROCESS-NAME,Weixin.exe
  - PROCESS-NAME,WeChat.exe
  - PROCESS-NAME,WeChatAppEx.exe
  - PROCESS-NAME,WechatBrowser.exe
  - PROCESS-NAME,WeChatPlayer.exe
  - PROCESS-NAME,QQ.exe
  - PROCESS-NAME,QQProtect.exe
  - PROCESS-NAME,QQApp.exe
  - PROCESS-NAME,TIM.exe
  - PROCESS-NAME,WeMeetApp.exe
  - PROCESS-NAME,TencentDocs.exe
  - PROCESS-NAME,QQLive.exe
  - PROCESS-NAME,QQMusic.exe
  - PROCESS-NAME,wegame.exe
  - PROCESS-NAME-REGEX,(?i)^Tencent.*\.exe$
  - PROCESS-NAME,DingTalk.exe
  - PROCESS-NAME,aDrive.exe
  - PROCESS-NAME,quark.exe
  - PROCESS-NAME,AliWangWang.exe
  - PROCESS-NAME,aliworkbench.exe
  - PROCESS-NAME,Taobao.exe
  - PROCESS-NAME,Alipay.exe
  - PROCESS-NAME-REGEX,(?i)^Ali.*\.exe$
  - PROCESS-NAME,Feishu.exe
  - PROCESS-NAME,Douyin.exe
  - PROCESS-NAME,JianYingPro.exe
  - PROCESS-NAME-REGEX,(?i)^ByteDance.*\.exe$
  - PROCESS-NAME,baidunetdisk.exe
  - PROCESS-NAME,baidunetdiskhost.exe
  - PROCESS-NAME,BaiduNetdiskRender.exe
  - PROCESS-NAME,QyClient.exe
  - PROCESS-NAME,QyKernel.exe
  - PROCESS-NAME-REGEX,(?i)^Baidu.*\.exe$
  - PROCESS-NAME,cloudmusic.exe
  - PROCESS-NAME,uu.exe
  - PROCESS-NAME,uugamebooster.exe
  - PROCESS-NAME,NemuPlayer.exe
  - PROCESS-NAME,NemuHeadless.exe
  - PROCESS-NAME-REGEX,(?i)^Netease.*\.exe$
  - PROCESS-NAME,wps.exe
  - PROCESS-NAME,wpp.exe
  - PROCESS-NAME,et.exe
  - PROCESS-NAME,wpspdf.exe
  - PROCESS-NAME,wpscloudsvr.exe
  - PROCESS-NAME,360tray.exe
  - PROCESS-NAME,360Safe.exe
  - PROCESS-NAME,HipsMain.exe
  - PROCESS-NAME,HipsTray.exe
  - PROCESS-NAME,Thunder.exe
  - PROCESS-NAME,ThunderVIP.exe
  - PROCESS-NAME,DownloadService.exe
  - PROCESS-NAME,Motrix.exe
  - PROCESS-NAME,SunloginClient.exe
  - PROCESS-NAME,ToDesk.exe
  - PROCESS-NAME,bilibili.exe
  - PROCESS-NAME,youkudesktop.exe
  - PROCESS-NAME,mgtv-client.exe
  - PROCESS-NAME,ImgoTV.exe
  - PROCESS-NAME,Kugou.exe
  - PROCESS-NAME,KwMusic.exe
  - PROCESS-NAME,ximalaya.exe
  - PROCESS-NAME,HuyaClient.exe
  - PROCESS-NAME,Douyu.exe
  - PROCESS-NAME,SogouExplorer.exe
  - PROCESS-NAME,Maxthon.exe
  - PROCESS-NAME,2345Explorer.exe
  - PROCESS-NAME,CentBrowser.exe
  - PROCESS-NAME,UCBrowser.exe
  - PROCESS-NAME,360se.exe
  - PROCESS-NAME,360chrome.exe
  - PROCESS-NAME,hexin.exe
  - PROCESS-NAME,futunn.exe
  - PROCESS-NAME,EastMoney.exe
  - PROCESS-NAME,YuanShen.exe
  - PROCESS-NAME,StarRail.exe
  - PROCESS-NAME,ZenlessZoneZero.exe
  - PROCESS-NAME,Wuthering Waves.exe
  - PROCESS-NAME-REGEX,(?i)^HoYo.*\.exe$